const data = [
  {
    id: 1,
    type: "home_and_furniture",
    title: "Hand Juicer",
    img: "./images/hand_juicer.png",
    price: 277,
    desc: "Description : Heavy duty alloy body and ergonomic handle. Your hands will never run out of effort when using our stroalg loy handles.",
    status: true,
  },
  {
    id: 2,
    type: "home_and_furniture",
    title: "Power & Hand Tool Kit",
    img: "./images/power_hand_tool_kit.png",
    price: 899,
    desc: "Description : IZOM Cordless Drill drives comes in a Corrugated box packed with Battery and Charger.",
    status: true,
  },
  {
    id: 3,
    type: "home_and_furniture",
    title: "Bed Cover",
    img: "./images/bed_cover.png",
    price: 299,
    desc: "Description : GooglyGoogly_Bring fresh style to your bedroom decor with the elegant colors of this beautiful fitted bed sheet set.",
    status: false,
  },
  {
    id: 4,
    type: "electronic",
    title: "APPLE iPhone 14",
    img: "./images/iphone.png",
    price: 999,
    desc: "Description : Stay productive and improve your performance with the Super Retina XDR display that is comfortable for the eyes. ",
    status: true,
  },
  {
    id: 5,
    type: "electronic",
    title: "Home Theatre ",
    img: "./images/home_theatre.png",
    price: 455,
    desc: "Description : It's time to enjoy a playback experience like never before courtesy boAt Blitz 1500, the 2.1 Channel Multimedia speaker with RGB LEDs.  ",
    status: true,
  },
  {
    id: 6,
    type: "grocery",
    title: "California Almonds",
    img: "./images/california_almonds.png",
    price: 455,
    desc: "Description : It's time to enjoy a playback experience like never before.  ",
    status: true,
  },
  {
    id: 7,
    type: "grocery",
    title: "Dry fruits",
    img: "./images/dry_fruits.png",
    price: 569,
    desc: "Description : 41 foods believes that our reputation must be based on the QUALITY of our products. ",
    status: false,
  },
];
export default data;
